version: "3.9"

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:26.4
    command: start-dev
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_PORT: 5432
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 1s
      timeout: 5s
      retries: 20
    depends_on:
      keycloak_db:
        condition: service_healthy
    volumes:
      - ./.docker/keycloak_data:/opt/keycloak/data

  keycloak_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - ./.docker/keycloak_db:/var/lib/postgresql/data